### ISSUE TITLE
Why i cannot retrieve my currently location?

### ISSUE THREAD

**Issue by kevinlee85** [varshylmobile/LocationManager#10]
Hi:
Recently, i used LocationManager to retrieve the user's current location with below codes:
var locationManager = LocationManager.sharedInstance
        locationManager.showVerboseMessage = true
        locationManager.autoUpdate = false
        locationManager.startUpdatingLocationWithCompletionHandler { (latitude, longitude, status, verboseMessage, error) -> () in

            println("lat:\(latitude) lon:\(longitude) status:\(status) error:\(error)")

            println(verboseMessage)

        }

But i found the completion handler never be called with no reasons.

Could you help me to figure out how make it works?
Thank you in advance.

**Comment by dougmcnerd** [comment]
I'm having the same issue. The completion handler is never called. I'm running Xcode 6.4 and iOS 8.4.

**Comment by fquintanilla** [comment]
Try with locationManager.autoUpdate = true

**Comment by varshylmobile** [comment]
should work with what @fquintanilla suggested. Closing this for now.

**Comment by dougmcnerd** [comment]
Sorry to be slow to respond. Yes, setting the locationManager.autoUpdate = true works.
