### ISSUE TITLE
Not updated for iOS 9

### ISSUE THREAD

**Issue by rtorcato** [varshylmobile/LocationManager#11]
Needs to be updated for Swift 2.

**Comment by Chilambuselvan** [comment]
Thanks! 
Looking Forward to have LocationManager updated for Swift2

**Comment by rtorcato** [comment]
any timeline for swift 2 support? Can we have a new dev branch for this?

**Comment by varshylmobile** [comment]
@rtorcato @Chilambuselvan  Please use latest commit.
