### ISSUE TITLE
problem with LocationManager in Swift 2.1

### ISSUE THREAD

**Issue by ylupan** [varshylmobile/LocationManager#17]
In Swift 2.1 I have 2 problem:

1. 'stringByAddingPercentEscapesUsingEncoding' was deprecated in iOS 9.0: Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.

2. 'sendAsynchronousRequest(_:queue:completionHandler:)' was deprecated in iOS 9.0: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h

please correct it

**Comment by dylanmaryk** [comment]
I have fixed these issues in my pull request: https://github.com/varshylmobile/LocationManager/pull/19
