### ISSUE TITLE
CocoaPod name is a duplicate

### ISSUE THREAD

**Issue by fraserscottmorrison** [varshylmobile/LocationManager#21]
I just spent 10 minutes trying to figure out why your documentation didn't match the LocationManager source. Its because `pod 'LocationManager', ~> '1'` will download a different pod.

You should use a unique name

At the very least you should update your ReadMe to show that you need this to install your pod
`pod 'LocationManager', :git => 'https://github.com/varshylmobile/LocationManager.git'`

**Comment by varshylmobile** [comment]
@fraserscottmorrison - Have made the changes.. thanks for bringing this up. 👍
