### ISSUE TITLE
It is not working in Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by anuragnc72** [varshylmobile/LocationManager#24]
Are you planning to support it for Xcode 8 or is there a workaround, I can use it in Xcode 8.
Thx

**Comment by kevinlee85** [comment]
I need the Swift3.0 version too.

**Comment by varshylmobile** [comment]
It would be great if someone could do a PR, I don't see myself working on it till this weekend.

**Comment by kevinlee85** [comment]
Thank you. Hope you can bring up to Swift3.0 soon.

**Comment by aornano** [comment]
There are 2 errors:
- for the "int1 is not convertible to Bool" add at the end of the line this : as NSString
- for the "ambiguous use of indexofobject(passingTest).." change the line as:
let index = inArray.indexOfObject(passingTest:) {obj, idx, stop in

**Comment by varshylmobile** [comment]
@aornano 👍 

@anuragnc72  @kevinlee85  please use the latest commit.

**Comment by aornano** [comment]
Very good, nice work!

**Comment by kevinlee85** [comment]
Awesome. Thank you.
