### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by efremidze** [varshylmobile/LocationManager#9]
Would you mind supporting CocoaPods?

**Comment by shanmarkus** [comment]
+ 1

**Comment by varshylmobile** [comment]
If somebody does a PR for that i would be happy to accept, I seldom get time to update this project.

**Comment by varshylmobile** [comment]
@efremidze 👍  Thanks for being so awesome, 
Closing #20 

![internet-high-five](https://cloud.githubusercontent.com/assets/1427616/15700580/4ad0fad8-27f2-11e6-9251-fda8e8d24551.jpg)
